server:
  port: 8081

spring:
  datasource:
    # allowMultiQueries=true: 允许MyBatis一次执行多条SQL语句
    url: jdbc:mysql://localhost:3306/xjp-boot?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: xuejingpan
    password: xuejingpan
    driver-class-name: com.mysql.cj.jdbc.Driver

# 日志
logging:
  level:
    root: info
    com.xuejingpan.xjpboot.dao.mapper: debug
